name: Build release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - uses: actions/setup-node@v1
    - run: npm run build
    - run: gh release create -d $(jq -r ".version" package.json) ./dist/*.js
