name: release nightly
on:
  push:
    branches:
      - develop
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - uses: actions/setup-node@v1
      - run: npm run build
      - run: (git push origin :refs/tags/nightly && git tag -d nightly) || true
      - run: gh release delete nightly -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
      - run: gh release create --prerelease --target develop -t nightly nightly ./dist/*.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
